name: social_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  iconsax: ^0.0.8
  flutter_svg: ^2.0.10+1
  flutter:
    sdk: flutter
  gap: ^3.0.1
  json_annotation: ^4.9.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  build_runner: ^2.4.10
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # assets (images & icons)
  assets:
    - assets/images/
    - assets/icons/

  # assets fonts
  fonts: 
    - family: SpaceGrotesk
      fonts: 
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
        - asset: assets/fonts/SpaceGrotesk-Light.ttf
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf